on:
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: Build
      run: dotnet build --configuration Release 
    - name: Pack
      run: dotnet pack --configuration Release --output .
    #- name: publish on version change
    #  id: publish_nuget
    #  uses: brandedoutcast/publish-nuget@v2
    #  with:
    #    PROJECT_FILE_PATH: BotLib/BotLib.csproj
    #    NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #    VERSION_FILE_PATH: BotLib/obj/gitversion.json
    #    VERSION_REGEX: '^.*?"SemVer": "(.*?)",$'
    #    INCLUDE_SYMBOLS: true
    - name: Publish package to NuGet
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
 