on:
  push:
    branches: [ "feature/*" ]
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/setup-dotnet@v2
      with:
        config-file: nuget.config
        source-url: https://nuget.pkg.github.com/thunderquack/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: Build
      run: dotnet build --configuration Release 
    - name: Pack
      run: dotnet pack --configuration Release --output .
    - name: Push
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}