on:
  push:
    branches: [ "feature/*" ]
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: Build
      run: dotnet build --configuration Release 
    - name: Pack
      run: dotnet pack --configuration Release --output .
    - name: publish on version change
      id: publish_nuget
      uses: brandedoutcast/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: BotLib/BotLib.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        VERSION_FILE_PATH: BotLib/obj/gitversion.json